### PR TITLE
WAITING FOR REVIEW: [Localization] it_IT Translation

### PR DESCRIPTION
**Pull request by fabriziocacicia**
I started the it_IT translation. 
I'm opening this PR to show the community that I started and to avoid that some others start too and redo the same things. 
By having this PR we could try to work on one single source.
Also, if for any reason I couldn't finish in a reasonable timeframe, anyone could start from my work instead of starting it from scratch.

(Do not merge as long as the status is 'WIP'!)
---------------------------------
### **STATUS: WAITING FOR REVIEW**

### CODE REVIEW

**Comment by guydavis** [comment]
This is great!  Given the [change you requested](https://github.com/guydavis/machinaris/issues/596), which I made into the `development` stream just now. I would recommend you point the MR at that development branch in this case.

**Comment by fabriziocacicia** [comment]
I was hoping to avoid switching the branch by cherry-picking the single commit where you made the change but, unfortunately, you included it in a broader one. So, I will switch to the `development` stream then.

**Comment by fabriziocacicia** [comment]
@guydavis I was able to cherry-pick only the change you made to the web `messages.po` file avoiding to switch the branch to `develop`.
See the commit I made 9e252a367af9d6402824a1aba063e59b795444ec

**Comment by fabriziocacicia** [comment]
Hi, I've been busy in the last few days. I think the web `messages.po` should be completed. I have to start the API one.

Please, give me another couple of days and I will complete the translation.

**Comment by fabriziocacicia** [comment]
I think I translated everything. Please check the files changed to make sure everything seems ok. 
After that, for me, you could merge it.

**Comment by guydavis** [comment]
This is great!  Thanks so much for your effort on this translation.  Really appreciated.

**Comment by fabriziocacicia** [comment]
If I'd known you were going to merge the PR instead of squashing all its commits into one, I would have reduced the number of commits I made 😅. Maybe next time.

**Pull request merged**
