### PR TITLE
Remove double spaces from localization files

### PR DESCRIPTION
**Pull request by fabriziocacicia**
I noticed that a lot of strings have double spaces.
If that doesn't cause too much trouble to the translation process and doesn't hurt anyone's work, I would suggest updating all the `messages.po` files removing them.

I already went through all the `messages.po` files of all the languages for both the `api` and `web` parts.
If everything looks good the PR should be already ready to be merged.

### CODE REVIEW

**Comment by guydavis** [comment]
Hi, for this to work, you'll need to touch every single source file that (*.py, *.html, etc) that references the `msgid`.  Otherwise, I believe, the i18n framework won't be able to line up the strings in the code to the strings in the messages.po files.  Because of this, I don't this MR can be merged as is.

**Comment by fabriziocacicia** [comment]
You are definitely right. I will try to add the necessary changes.

**Comment by guydavis** [comment]
Okay, if you think that is warranted for some double spaces.  That means a change to many, many source code files.   What about just removing the double spaces from the translated `it_IT`  messages.po, but only in `msgstr`.  Then your translations don't have double-spaces, the way you want. As long as you only change the `msgstr`, not the `msgid` then nothing else in code (or in other translations) needs to change.

I welcome your opinion.  Thanks again for your help.

**Comment by fabriziocacicia** [comment]
I was just asking. 
If you think that the changes I proposed are too invasive I respect and accept your opinion. 
Applying the changes only to the Italian language files should be enough, at least for now.

**Pull request closed without merging**
