### PR TITLE
Add German translation to WebUI.

### PR DESCRIPTION
**Pull request by ApfelBirneKreis**
Added German Translation to WebUi

### CODE REVIEW

**Comment by guydavis** [comment]
Awesome!  Really appreciate this contribution.  Would you mind also translating this [list of landing page lines](https://github.com/guydavis/machinaris/blob/develop/web/static/landings/de_DE.txt) into German as well?  Or just editing them to be better/funnier ones.  Feel free to delete any that aren't funny or translate well.  The goal is a plain text file of German landing lines, instead of the English placeholders currently in that file.  Thanks!

**Comment by ApfelBirneKreis** [comment]
yeah i can do that. but most of them only make sense in english. I'll think about a few funny ones in german.

**Comment by ApfelBirneKreis** [comment]
Translation of the Landing pages done.

I'll improve the translations over time. If somebody notices something tag me on Discord or here.

**Comment by guydavis** [comment]
Thanks!  Testing message compilation now.  Should be available in development stream later today.

**Pull request merged**
